# Generated by Django 4.1.7 on 2023-02-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_event_selection_vote_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Moderation', 'На модерации'), ('Approved', 'Одобрено')], default='Moderation', max_length=10, verbose_name='Статус'),
        ),
    ]
