# Generated by Django 4.1.7 on 2023-02-22 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_post_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default=1, max_length=300, verbose_name='Предположительная дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Дата проведения'),
            preserve_default=False,
        ),
    ]
