# Generated by Django 4.1.7 on 2023-02-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_event_date_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=300, verbose_name='Предположительная дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(max_length=300, verbose_name='Дата проведения'),
        ),
    ]
