# Generated by Django 4.1.7 on 2023-02-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_alter_event_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'selection')},
        ),
    ]
