# Generated by Django 4.1.7 on 2023-02-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='models_app.event', verbose_name='Событие'),
        ),
    ]
