# Generated by Django 4.1.7 on 2023-02-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_alter_selection_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='models_app.selection', verbose_name='Выбор'),
        ),
    ]
