# Generated by Django 4.1.7 on 2023-02-23 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_alter_vote_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
