# Generated by Django 4.1.7 on 2023-02-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True, max_length=300, verbose_name='Дата проведения'),
        ),
    ]
