# Generated by Django 4.1.7 on 2023-02-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='models_app.event', verbose_name='Событие'),
        ),
    ]
