# Generated by Django 4.1.7 on 2023-03-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0016_remove_comment_post_comment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='models_app.thread', verbose_name='Тред'),
        ),
    ]
