# Generated by Django 4.1.7 on 2023-04-17 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0017_alter_comment_thread'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], default=datetime.date(2023, 4, 17), max_length=10, verbose_name='Голос'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'choice')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='selection',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
