# Generated by Django 4.1.7 on 2023-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0017_alter_comment_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events/', verbose_name='Изображение'),
        ),
    ]
