# Generated by Django 4.1.7 on 2023-04-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0019_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models_app.event', verbose_name='Событие'),
            preserve_default=False,
        ),
    ]
