# Generated by Django 4.1.7 on 2023-04-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0018_event_image'),
        ('models_app', '0021_alter_vote_event_alter_vote_user'),
    ]

    operations = [
    ]
