# Generated by Django 4.1.7 on 2023-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0022_merge_20230417_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/', verbose_name='Изображение'),
        ),
    ]
