# Generated by Django 4.1.7 on 2023-04-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0023_alter_event_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'event')},
        ),
    ]
