# Generated by Django 4.1.7 on 2023-05-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0024_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(max_length=300, verbose_name='Дата проведения'),
        ),
    ]
